apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: helloworld
      app.kubernetes.io/name: helloworld
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: helloworld
        app.kubernetes.io/name: helloworld
      name: helloworld
    spec:
      volumes:
      - name: standalone
        configMap:
          name: standalone
      containers:
      - volumeMounts:
        - name: standalone
          mountPath: /opt/eap/standalone/configuration/standalone.xml
          subPath: standalone.xml
        env:
        - name: ROOT_LOGGER_LEVEL
          value: "INFO"
        - name: JGROUPS_PING_PROTOCOL
          value: dns.DNS_PING
        - name: OPENSHIFT_DNS_PING_SERVICE_PORT
          value: "8888"
        - name: ENABLE_GENERATE_DEFAULT_DATASOURCE
          value: "false"
        - name: OPENSHIFT_DNS_PING_SERVICE_NAME
          value: helloworld-ping
        - name: ENV_FILES
          value: /etc/extensions/*
        image: quay.io/mamoru1112/helloworld
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: admin
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: helloworld
        ports:
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8888
          name: ping
          protocol: TCP
        - containerPort: 9990
          name: admin
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: admin
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: admin
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
